# Generated by Django 4.2 on 2023-05-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchid', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('positionid', models.AutoField(primary_key=True, serialize=False)),
                ('positionname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('refereeid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadiumid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('sponsor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournamentid', models.AutoField(primary_key=True, serialize=False)),
                ('totalprizepool', models.PositiveIntegerField()),
                ('sponsor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('priority', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('dob', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Stat',
            fields=[
                ('teamstatid', models.AutoField(primary_key=True, serialize=False)),
                ('standing', models.PositiveIntegerField()),
                ('goals', models.PositiveIntegerField()),
                ('goalsconceded', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('loses', models.PositiveIntegerField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_stat', to='login.team')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('resultid', models.AutoField(primary_key=True, serialize=False)),
                ('attackerpts', models.PositiveIntegerField()),
                ('defenderpts', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.match')),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('practiceid', models.AutoField(primary_key=True, serialize=False)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.stadium')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Stat',
            fields=[
                ('playerstatid', models.AutoField(primary_key=True, serialize=False)),
                ('numberofgoals', models.PositiveIntegerField()),
                ('numberofassists', models.PositiveIntegerField()),
                ('apperances', models.PositiveIntegerField()),
                ('redcards', models.PositiveIntegerField()),
                ('yellowcards', models.PositiveIntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_stat', to='login.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.position'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.team'),
        ),
        migrations.CreateModel(
            name='ParticipateIn',
            fields=[
                ('participateid', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='attacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacker', to='login.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='defender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender', to='login.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.stadium'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.tournament'),
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('fanid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.team')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coachid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(auto_now_add=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='login.team')),
            ],
        ),
    ]
