# Generated by Django 4.2 on 2023-06-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, upload_to='players_photos/'),
        ),
    ]
