# Generated by Django 4.2 on 2023-06-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_player_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, upload_to='players_images/'),
        ),
    ]
