# Generated by Django 4.2 on 2023-06-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_player_photo_player_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='coach',
            name='coach_image',
            field=models.ImageField(blank=True, upload_to='coachs_images/'),
        ),
        migrations.AddField(
            model_name='team',
            name='sponsor_image',
            field=models.ImageField(blank=True, upload_to='sponsors_images/'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_image',
            field=models.ImageField(blank=True, upload_to='teams_images/'),
        ),
    ]
