# Generated by Django 4.2 on 2023-06-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_delete_user_coach_coach_image_team_sponsor_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('nationid', models.AutoField(primary_key=True, serialize=False)),
                ('nation_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='name',
            new_name='coach_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
        migrations.AlterField(
            model_name='coach',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.nation'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.nation'),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.nation'),
        ),
    ]
