# Generated by Django 4.2 on 2023-06-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_nation_rename_name_coach_coach_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsorid', models.AutoField(primary_key=True, serialize=False)),
                ('sponsor_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sponsor_image',
        ),
        migrations.AlterField(
            model_name='fan',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.nation'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.nation'),
        ),
        migrations.AddField(
            model_name='team',
            name='sponsors',
            field=models.ManyToManyField(to='login.sponsor'),
        ),
    ]
