# Generated by Django 4.2 on 2023-06-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_sponsor_remove_team_sponsor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='dob',
            field=models.DateField(),
        ),
    ]
