# Generated by Django 4.2 on 2023-06-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_coach_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_stat',
            name='standing',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='tournament',
            name='sponsor',
            field=models.ManyToManyField(to='login.sponsor'),
        ),
    ]
