# Generated by Django 4.2 on 2023-06-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_team_stat_standing_remove_tournament_sponsor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dob',
            field=models.DateField(),
        ),
    ]
