# Generated by Django 4.2 on 2023-06-11 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_player_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.RemoveField(
            model_name='player',
            name='phone',
        ),
        migrations.AddField(
            model_name='player',
            name='player_type',
            field=models.CharField(default='local', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.ForeignKey(default='England', on_delete=django.db.models.deletion.CASCADE, to='login.nation'),
        ),
    ]
