# Generated by Django 4.2 on 2023-06-11 08:48

from django.db import migrations, models
import django.db.models.deletion
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_coach_email_remove_coach_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.ForeignKey(default=login.models.get_default_nation, on_delete=django.db.models.deletion.CASCADE, to='login.nation'),
        ),
    ]
