# Generated by Django 4.2 on 2023-06-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_team_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
