# Generated by Django 4.2 on 2023-06-11 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_player_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('fixtureid', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='participatein',
            name='team',
        ),
        migrations.RemoveField(
            model_name='participatein',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='stadium',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='team',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='result',
            name='match',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='address',
        ),
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.stadium'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player_stat',
            name='apperances',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stat',
            name='numberofassists',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stat',
            name='numberofgoals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stat',
            name='redcards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player_stat',
            name='yellowcards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_stat',
            name='goals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_stat',
            name='goalsconceded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_stat',
            name='loses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_stat',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='ParticipateIn',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.DeleteModel(
            name='Referee',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AddField(
            model_name='fixture',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.stadium'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacker', to='login.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender', to='login.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.tournament'),
        ),
    ]
