# Generated by Django 4.2 on 2023-06-12 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_remove_fixture_tournament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='day',
            new_name='time',
        ),
    ]
