# Generated by Django 4.2 on 2023-06-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_goalevent_goaltype_team_stat_pts_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='status',
            field=models.CharField(default='Upcoming', max_length=255),
        ),
    ]
