# Generated by Django 4.2 on 2023-06-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_fixture_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_stat',
            name='draws',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
