# Generated by Django 4.2 on 2023-06-12 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_team_stat_draws'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('roundid', models.AutoField(primary_key=True, serialize=False)),
                ('round_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='fixture',
            name='round_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roundname', to='login.round'),
        ),
    ]
