# Generated by Django 4.2 on 2023-06-12 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_alter_round_round_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusid', models.AutoField(primary_key=True, serialize=False)),
                ('statusname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='fixture',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.status'),
        ),
    ]
