# Generated by Django 4.2 on 2023-06-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_alter_goalevent_goal_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('regulationid', models.AutoField(primary_key=True, serialize=False)),
                ('minage', models.IntegerField(default=16)),
                ('maxage', models.IntegerField(default=40)),
                ('minplayer', models.IntegerField(default=15)),
                ('maxplayer', models.IntegerField(default=22)),
                ('maxforeignplayer', models.IntegerField(default=3)),
                ('winpts', models.IntegerField(default=3)),
                ('drawpts', models.IntegerField(default=1)),
                ('losepts', models.IntegerField(default=0)),
                ('scoretime', models.IntegerField(default=90)),
            ],
        ),
    ]
