# Generated by Django 4.2 on 2023-06-13 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_team_stat_goaldifferencce'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalevent',
            name='assist_player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assisted_goal_events', to='login.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goalevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scored_goal_events', to='login.player'),
        ),
    ]
