# Generated by Django 4.2 on 2023-06-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_goalevent_assist_player_alter_goalevent_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_stat',
            old_name='goaldifferencce',
            new_name='goaldifference',
        ),
    ]
