# Generated by Django 4.2 on 2023-06-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_rename_goaldifferencce_team_stat_goaldifference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round_name',
            field=models.CharField(max_length=100),
        ),
    ]
