# Generated by Django 4.2 on 2023-06-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0037_alter_result_goal_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='goalevent',
            name='assist_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assisted_goal_events', to='login.player'),
        ),
    ]
