# Generated by Django 4.2 on 2023-06-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0038_alter_fixture_time_alter_goalevent_assist_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalevent',
            name='assist_player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assisted_goal_events', to='login.player'),
            preserve_default=False,
        ),
    ]
