# Generated by Django 4.2 on 2023-06-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_alter_goalevent_assist_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalevent',
            name='assist_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assisted_goal_event', to='login.player'),
        ),
        migrations.AlterField(
            model_name='goalevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scored_goal_event', to='login.player'),
        ),
        migrations.AlterField(
            model_name='goalevent',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_event', to='login.result'),
        ),
    ]
