# Generated by Django 4.1.7 on 2023-06-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0041_alter_goalevent_assist_player_alter_goalevent_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_stat',
            name='numberofassists',
            field=models.IntegerField(default=0),
        ),
    ]
